# Generated by Django 5.2.7 on 2025-10-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuName', models.CharField(max_length=100)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('religion', models.TextField(blank=True, max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('fLang', models.CharField(blank=True, max_length=20)),
                ('oLang', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('healthCon', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='emergencyContact1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, max_length=150)),
                ('contact', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='emergencyContact2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, max_length=150)),
                ('contact', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='emergencyContact3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, max_length=150)),
                ('contact', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ftherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FtherName', models.TextField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('eduQualification', models.TextField(blank=True, max_length=150)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('desingation', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FtherName', models.TextField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('eduQualification', models.TextField(blank=True, max_length=150)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('desingation', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='mtherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FtherName', models.TextField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('eduQualification', models.TextField(blank=True, max_length=150)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('desingation', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='schUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320)),
                ('subject', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, max_length=600)),
                ('pic', models.ImageField(upload_to='pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
